services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
    networks:
      - w2m
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: w2m-api
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PWD: guest
    depends_on:
      rabbitmq:
          condition: service_healthy
    links:
      - rabbitmq
    ports:
      - "8080:8080"    
    networks:
      - w2m
networks:
  w2m:
    driver: bridge
